[package]
name = "rudish"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4"
rudish_lib = {path = "../RustroverProjects/rudish_lib"}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.release]
debug = true